from selenium.webdriver.common.by import By

FIRST_QUESTION = (By.XPATH, "//div[@id = 'accordion__heading-0']")
FIRST_QUESTION_OPEN = (By.XPATH, "//div[@id ='accordion__panel-0']/p")
SECOND_QUESTION = (By.XPATH, "//div[@id = 'accordion__heading-1']")
SECOND_QUESTION_OPEN = (By.XPATH, "//div[@id = 'accordion__panel-1']/p")
THIRD_QUESTION = (By.XPATH, "//div[@id = 'accordion__heading-2']")
THIRD_QUESTION_OPEN = (By.XPATH, "//div[@id = 'accordion__panel-2']/p")
FOURTH_QUESTION = (By.XPATH, "//div[@id = 'accordion__heading-3']")
FOURTH_QUESTION_OPEN = (By.XPATH, "//div[@id = 'accordion__panel-3']/p")
FIFTH_QUESTION = (By.XPATH, "//div[@id = 'accordion__heading-4']")
FIFTH_QUESTION_OPEN = (By.XPATH, "//div[@id = 'accordion__panel-4']/p")
SIXTH_QUESTION = (By.XPATH, "//div[@id = 'accordion__heading-5']")
SIXTH_QUESTION_OPEN = (By.XPATH, "//div[@id = 'accordion__panel-5']/p")
SEVENTH_QUESTION = (By.XPATH, "//div[@id = 'accordion__heading-6']")
SEVENTH_QUESTION_OPEN = (By.XPATH, "//div[@id = 'accordion__panel-6']/p")
EIGHTH_QUESTION = (By.XPATH, "//div[@id = 'accordion__heading-7']")
EIGHTH_QUESTION_OPEN = (By.XPATH, "//div[@id ='accordion__panel-7']/p")
SCOOTER_IMG = (By.XPATH, "//img[@src= '/assets/scooter.png']")
SCOOTER_LOGO = (By.XPATH, "//img[@alt='Scooter']")
TOP_ORDER_BUTTON = (By.XPATH, "//button[@class='Button_Button__ra12g']")
YANDEX_LOGO = (By.XPATH, "//img[contains(@alt,'Yandex')]")
DZEN_SEARCH_BUTTON = (By.XPATH, "//button[contains(.,'Найти')]")  # хз что это
