from selenium.webdriver.common.by import By

NAME_FIELD = (By.XPATH, "//input[contains(@placeholder,'* Имя')]")
SURNAME_FIELD = (By.XPATH, "//input[contains(@placeholder,'* Фамилия')]")
ADDRESS_FIELD = (By.XPATH, "//input[contains(@placeholder,'* Адрес: куда привезти заказ')]")
METRO_FIELD = (By.XPATH, "//input[contains(@placeholder,'* Станция метро')]")
PHONE_FIELD = (By.XPATH, "//input[contains(@placeholder,'* Телефон: на него позвонит курьер')]")
ORDER_BUTTON_UPPER = (By.XPATH, "//div[@class='Header_Nav__AGCXC']/button[text()='Заказать']")
STATION_SOKOLNIKI = (By.XPATH, "//li[@data-value='4']")
STATION_OHOTNYI_RYAD = (By.XPATH, "//li[@data-value='10']")
NEXT_BUTTON = (By.XPATH, "//button[text() = 'Далее']")
DATE_FIELD = (By.XPATH, "//input[contains(@placeholder,'* Когда привезти самокат')]")
DATA1_CHOOSE = (By.XPATH, "//div[@class= 'react-datepicker__week'][1]/div[1]")
DATA2_CHOOSE = (By.XPATH, "//div[@class= 'react-datepicker__week'][2]/div[3]")
RENTAL_TIME_FIELD = (By.XPATH, "//div[@aria-haspopup='listbox']")
RENT_TWO_DAYS = (By.XPATH, "//div[@class= 'Dropdown-option' and contains(text(), 'двое суток')]")
RENT_FIVE_DAYS = (By.XPATH, "//div[@class= 'Dropdown-option' and contains(text(), 'пятеро суток')]")
BLACK_COLOR_SCOOTER = (By.XPATH, "//input[@id='black']")
GREY_COLOR_SCOOTER = (By.XPATH, "//input[@id='grey']")
COMMENT_FIELD = (By.XPATH, "//input[@placeholder='Комментарий для курьера']")
ORDER_BUTTON_LOWER = (By.XPATH, "(//button[text()='Заказать'])[2]")
ACCEPT_BUTTON = (By.XPATH, "//button[contains(.,'Да')]")
SEE_STATUS_BUTTON = (By.XPATH, "//button[text()='Посмотреть статус']")
